import Link from "next/link";
import { Header, Footer } from "../../components/Shell";

const actions = [
  {title:"Find your requirements", body:"Answer a few questions to see the documents, fees, and legal steps that apply to you.", href:"/en/acts", label:"Open Act finder"},
  {title:"Check an application", body:"See where your registration stands using your application number and date of birth.", href:"/en/status", label:"Check status"},
  {title:"Find a registration office", body:"Locate the registrar responsible for your district, sub-division, or police station area.", href:"/en/offices", label:"Find an office"}
];

export default async function Home(){return <main>
  <Header locale="en" />
  <section className="page grid gap-12 py-16 md:grid-cols-[1.05fr_.95fr] md:items-center md:py-24"><div><p className="mb-5 text-xs font-bold uppercase tracking-[.18em] text-teal">Office of the Registrar General of Marriages</p><h1 className="max-w-xl text-5xl leading-[.98] md:text-7xl">Marriage registration, made clearer.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-[var(--muted)]">The modern citizen gateway for West Bengal’s marriage registration services. Choose the Act, understand the process, and reach the right Marriage Officer.</p><div id="act-finder" className="mt-9 border border-rule bg-surface p-5 shadow-[0_12px_28px_rgba(23,33,31,.08)]"><label htmlFor="act" className="mb-2 block text-sm font-bold">Which service do you need?</label><div className="flex flex-col gap-3 sm:flex-row"><select id="act" className="focus min-h-12 flex-1 border border-rule bg-paper px-4 text-sm"><option>Choose a Marriage Act</option><option>Hindu Marriage Act, 1955</option><option>Special Marriage Act, 1954 · Section 13</option><option>Special Marriage Act, 1954 · Section 16</option><option>Indian Christian Marriage Act, 1872</option><option>Parsi Marriage &amp; Divorce Act, 1936</option></select><Link href="/en/acts" className="focus inline-flex min-h-12 items-center justify-center bg-saffron px-5 text-sm font-bold">View requirements</Link></div><p className="mt-3 text-xs text-[var(--muted)]">Official guidance, timelines, and required documents.</p></div></div><div className="ledger relative min-h-[390px] overflow-hidden p-7 md:p-10"><div className="absolute right-6 top-6 rounded-full border border-saffron bg-saffron-tint px-3 py-1 text-[10px] font-bold uppercase tracking-widest text-teal">West Bengal MARREG</div><div className="mt-12 max-w-sm"><p className="text-xs font-bold uppercase tracking-[.18em] text-[var(--muted)]">A public record with purpose</p><h2 className="mt-5 text-4xl leading-tight">We register marriages. We add value to marriages.</h2><p className="mt-5 text-sm leading-7 text-[var(--muted)]">A secure digital record supports citizens through legal separation, citizenship, inheritance, and other legal and social matters.</p></div><div className="absolute bottom-10 left-10 right-10 border-b-2 border-ink pb-3 font-display text-2xl italic">Registrar’s record</div><div className="absolute bottom-4 right-10 text-[10px] font-bold uppercase tracking-widest text-[var(--muted)]">RGM · West Bengal</div></div></section>
  <section className="border-y border-rule bg-surface"><div className="page grid gap-0 md:grid-cols-3">{actions.map((a,i)=><article key={a.title} className="border-rule py-8 md:border-r md:px-8 md:first:pl-0 md:last:border-0 md:last:pr-0"><span className="font-display text-3xl text-saffron">0{i+1}</span><h2 className="mt-4 text-2xl">{a.title}</h2><p className="mt-3 min-h-16 text-sm leading-6 text-[var(--muted)]">{a.body}</p><Link className="focus mt-5 inline-block border-b-2 border-saffron pb-1 text-sm font-bold text-teal" href={a.href}>{a.label} <span aria-hidden="true">→</span></Link></article>)}</div></section>
  <section id="requirements" className="page grid gap-10 py-16 md:grid-cols-[1fr_1.2fr] md:py-24"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-teal">Built on the record</p><h2 className="mt-4 text-4xl">Know what you can trust.</h2></div><div className="space-y-5 text-sm leading-7 text-[var(--muted)]"><p>Every requirement links back to an official act, notice, or service source. We show when it was last checked so you can make decisions with the full context.</p><div className="flex gap-4 border-l-2 border-saffron pl-5"><span className="font-display text-2xl text-teal">✓</span><p><strong className="text-ink">Source-first guidance.</strong><br/>Plain-language summaries never replace the law. They help you reach it.</p></div></div></section>
  <section className="border-y border-rule bg-surface"><div className="page grid gap-4 py-12 md:grid-cols-4"><Link href="/en/apply" className="focus border border-rule p-5"><span className="text-xs font-bold uppercase tracking-widest text-teal">Service</span><h2 className="mt-3 text-2xl">Apply online</h2><p className="mt-2 text-sm text-[var(--muted)]">Start or resume an application.</p></Link><Link href="/en/status" className="focus border border-rule p-5"><span className="text-xs font-bold uppercase tracking-widest text-teal">Service</span><h2 className="mt-3 text-2xl">Track status</h2><p className="mt-2 text-sm text-[var(--muted)]">View application updates.</p></Link><Link href="/en/offices" className="focus border border-rule p-5"><span className="text-xs font-bold uppercase tracking-widest text-teal">Directory</span><h2 className="mt-3 text-2xl">Online MO</h2><p className="mt-2 text-sm text-[var(--muted)]">Find Marriage Officers and offices.</p></Link><Link href="/en/help" className="focus border border-rule p-5"><span className="text-xs font-bold uppercase tracking-widest text-teal">Public information</span><h2 className="mt-3 text-2xl">Notices &amp; help</h2><p className="mt-2 text-sm text-[var(--muted)]">FAQs, circulars, fees, and guidance.</p></Link></div></section>
  <Footer />
</main>}
